# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS build


# Set working directory
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy the built JAR from the build stage
COPY --from=build /app/target/quiz-0.0.1-SNAPSHOT.jar .

# Expose the port
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "quiz-0.0.1-SNAPSHOT.jar"]